{{- if le .Capabilities.KubeVersion.Major "1" }}
{{- if le .Capabilities.KubeVersion.Minor "7" }}
apiVersion: "batch/v2alpha1"
{{- else }}
apiVersion: "batch/v1beta1"
{{- end }}
{{- end }}
kind: CronJob
metadata:
  name: {{.Values.name}}
spec:
  schedule: {{.Values.schedule}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{.Values.name}}
            image: {{.Values.image}}
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: OnFailure
